# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  push:
    paths:
      - "pattern_2_with-python/**"
      - ".github/workflows/python-app.yml"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./pattern_2_with-python/
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: ./pattern_2_with-python/
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build a test config
      working-directory: ./pattern_2_with-python/
      run: echo '{"discord":{"webhook":{"url":"${{ secrets.GHA_Test_Discord }}", "embed":{"image":{"url":""}},"at_mention":[]}},"ipinfo":{"auth":{"token":"${{ secrets.GHA_Test_Ipinfo }}"}}}' | jq -c | tee login-notice.json
    - name: Test with pytest
      working-directory: ./pattern_2_with-python/
      run: |
        pytest *.py
    - run: |
        ls -lhA
      if: failure()
      working-directory: ./pattern_2_with-python/
    - run: |
        tree
      if: failure()
      working-directory: ./pattern_2_with-python/
    - run: |
        env | grep ^GITHUB
      if: failure()
      working-directory: ./pattern_2_with-python/
    - name: cat login-notice.json
      run: |
        cat login-notice.json | jq -c | base64
      if: failure()
      working-directory: ./pattern_2_with-python/
    - name: upload login-notice.json
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: sample-config
        path: ./pattern_2_with-python/login-notice.json
    - name: upload login-notice.dat
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: debug-config
        path: ./pattern_2_with-python/login-notice-json.dat
